name: PHP Build

on: [push]

jobs:
  build:
   runs-on: ubuntu-22.04
   strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2', '8.3']

   steps:

    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: composer

    - name: Install xmlstarlet
      run: sudo apt-get install -y xmlstarlet

    - name: Install nmap
      run: sudo apt-get install -y nmap

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run lint
      run: composer lint

    - name: Run psalm
      run: ./vendor/bin/psalm.phar --php-version=${{ matrix.php-versions }} --output-format=github

    - name: Run phpunit
      run: composer phpunit
